server:
  port: 8081
spring:
  application:
    name: wzy
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/viplounge?useSSL=false&serverTimezone=UTC
    username: root
    password: Wzy20200901@
  redis:
    host: 192.168.150.101
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#mybatis-plus:
#  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.wzy: debug

pay:
  alipay:
    # 刚才在支付宝后台复制的【支付宝公钥】（注意不是应用公钥）
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...

    # 下面这两个如果不填，代码会读取默认值，建议填上明确一下
    charset: UTF-8
    sign-type: RSA2

mybatis:
  # spring boot运行的是类路径,不是绝对路径
  # 正确写法：直接从 classpath 根目录开始找
  mapper-locations: classpath:mappers/PaymentMapper.xml



